const loginActionTypes = {
  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  USER_LOGOUT: "USER_LOGOUT",
  TOKEN_LOADING: "TOKEN_LOADING",
  TOKEN_VERIFIED: "TOKEN_VERIFIED",
  TOKEN_NOTVERIFIED: "TOKEN_NOTVERIFIED",
};

export default loginActionTypes;
