const loginActionTypes = {
  LOGGEDIN: 'LOGGEDIN',
  USER_LOGIN_REQUEST : 'USER_LOGIN_REQUEST', 
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
  USER_LOGOUT: 'USER_LOGOUT'
};

export default loginActionTypes;
