export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const PROFILE_CREATE_REQUEST = "PROFILE_CREATE_REQUEST";
export const PROFILE_CREATE_SUCCESS = "PROFILE_CREATE_SUCCESS";
export const PROFILE_CREATE_FAIL = "PROFILE_CREATE_FAIL";
export const PROFILE_CREATE_RESET = "PROFILE_CREATE_RESET";

export const WISHLIST_ADD_REQUEST = "WISHLIST_ADD_REQUEST";
export const WISHLIST_ADD_SUCCESS = "WISHLIST_ADD_SUCCESS";
export const WISHLIST_ADD_FAIL = "WISHLIST_ADD_FAIL";

export const WISHLIST_DELETE_REQUEST = "WISHLIST_DELETE_REQUEST";
export const WISHLIST_DELETE_SUCCESS = "WISHLIST_DELETE_SUCCESS";
export const WISHLIST_DELETE_FAIL = "WISHLIST_DELETE_FAIL";
